services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: findthem-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - findthem-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: findthem-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - findthem-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  findthem-network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend:
